spring.application.name=sport-tournament-manager

# Thông tin kết nối bằng Service Account (SEC_ADMIN)
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1
spring.datasource.username=SEC_ADMIN
spring.datasource.password=SEC_ADMIN
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Cấu hình HikariCP tối ưu cho Oracle
spring.datasource.hikari.pool-name=SportHikariPool
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-test-query=SELECT 1 FROM DUAL

# JWT Security Configuration
# Khóa bí mật (Secret Key) phải đủ dài và an toàn
jwt.secret=HcmuteSportTournamentManagerSecretKey2026Secure!!!
# Thời gian sống của Token (Ví dụ: 86400000 ms = 24 giờ)
jwt.expiration=86400000

spring.jpa.hibernate.ddl-auto=none

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=thi272005@gmail.com
spring.mail.password=zdha feih babg fdwi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.com.hcmute.sportms=DEBUG