ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER SPORTS_OWNER IDENTIFIED BY "CNTT2026!";
GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE PROCEDURE TO SPORTS_OWNER;
ALTER USER SPORTS_OWNER QUOTA UNLIMITED ON USERS;

ALTER USER SEC_ADMIN IDENTIFIED BY "SEC_ADMIN";
GRANT CONNECT, RESOURCE, CREATE PROCEDURE TO SEC_ADMIN;

GRANT EXEMPT REDACTION POLICY TO SEC_ADMIN;
GRANT EXECUTE ON DBMS_RLS TO SEC_ADMIN;    
GRANT EXECUTE ON DBMS_CRYPTO TO SEC_ADMIN; 
GRANT EXECUTE ON DBMS_REDACT TO SEC_ADMIN;

GRANT CREATE ANY CONTEXT TO SEC_ADMIN;
GRANT DROP ANY CONTEXT TO SEC_ADMIN;
GRANT SELECT ANY TABLE TO SEC_ADMIN;