ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER SPORTS_OWNER IDENTIFIED BY "CNTT2026!";
GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE PROCEDURE TO SPORTS_OWNER;
ALTER USER SPORTS_OWNER QUOTA UNLIMITED ON USERS;

ALTER USER SEC_ADMIN IDENTIFIED BY "SEC_ADMIN";
GRANT CONNECT, RESOURCE, CREATE PROCEDURE TO SEC_ADMIN;

GRANT EXEMPT REDACTION POLICY TO SEC_ADMIN;
GRANT EXECUTE ON DBMS_RLS TO SEC_ADMIN;    
GRANT EXECUTE ON DBMS_CRYPTO TO SEC_ADMIN; 
GRANT EXECUTE ON DBMS_REDACT TO SEC_ADMIN;
GRANT EXECUTE ON SYS.DBMS_SESSION TO SEC_ADMIN;

GRANT CREATE ANY CONTEXT TO SEC_ADMIN;
GRANT DROP ANY CONTEXT TO SEC_ADMIN;
GRANT SELECT ANY TABLE TO SEC_ADMIN;
GRANT ADMINISTER REDACTION POLICY TO SEC_ADMIN;

GRANT DBA TO SEC_ADMIN;
GRANT LBAC_DBA TO SEC_ADMIN;
ALTER USER SEC_ADMIN DEFAULT ROLE ALL;
GRANT EXECUTE ON LBACSYS.SA_SYSDBA       TO SEC_ADMIN;
GRANT EXECUTE ON LBACSYS.SA_COMPONENTS   TO SEC_ADMIN;
GRANT EXECUTE ON LBACSYS.SA_LABEL_ADMIN  TO SEC_ADMIN;
GRANT EXECUTE ON LBACSYS.LBAC_POLICY_ADMIN TO SEC_ADMIN;
GRANT EXECUTE ON LBACSYS.SA_USER_ADMIN   TO SEC_ADMIN;
GRANT EXECUTE ON LBACSYS.TO_LBAC_DATA_LABEL TO SEC_ADMIN;
GRANT INHERIT PRIVILEGES ON USER LBACSYS TO SEC_ADMIN;
