SET SERVEROUTPUT ON;
SET ECHO ON;

-- CHỈNH SỬA LOGIC HÀM VPD CHO BẢNG AUDIT_LOG
CONN SEC_ADMIN/SEC_ADMIN;

CREATE OR REPLACE FUNCTION SEC_ADMIN.FN_VPD_AUDIT (
    p_schema VARCHAR2,
    p_object VARCHAR2
) RETURN VARCHAR2 AS
    v_role VARCHAR2(20);
    v_team VARCHAR2(20);
BEGIN
    v_role := SYS_CONTEXT('SPORT_CTX','ROLE');
    v_team := SYS_CONTEXT('SPORT_CTX','TEAM_ID');

    IF v_role = 'ROLE_BTC' THEN
        RETURN '1=1';
    ELSIF v_role = 'ROLE_TD' THEN
        RETURN 'TeamCode='''||v_team||'''';
    ELSE
        RETURN '1=2'; 
    END IF;
END;
/

-- TRIỂN KHAI ORACLE LABEL SECURITY (OLS)
CONN LBACSYS/LBACSYS;

BEGIN
    SA_SYSDBA.CREATE_POLICY(
        policy_name => 'SPORT_POLICY',
        column_name => 'OLS_LABEL'
    );
END;
/
EXEC SA_SYSDBA.ENABLE_POLICY('SPORT_POLICY');
GRANT SPORT_POLICY_DBA TO SEC_ADMIN;

-- Chuyển quyền quản trị Policy cho SEC_ADMIN
CONN SEC_ADMIN/SEC_ADMIN;

BEGIN
    -- 1. Levels
    SA_COMPONENTS.CREATE_LEVEL('SPORT_POLICY', 100, 'PUBLIC', 'Public');
    SA_COMPONENTS.CREATE_LEVEL('SPORT_POLICY', 200, 'INTERNAL', 'Internal');
    SA_COMPONENTS.CREATE_LEVEL('SPORT_POLICY', 300, 'CONFIDENTIAL', 'Confidential');
    SA_COMPONENTS.CREATE_LEVEL('SPORT_POLICY', 400, 'SECRET', 'Secret');

    -- 2. Compartments
    SA_COMPONENTS.CREATE_COMPARTMENT('SPORT_POLICY', 10, 'MATCH', 'Match');
    SA_COMPONENTS.CREATE_COMPARTMENT('SPORT_POLICY', 20, 'TEAM', 'Team');
    SA_COMPONENTS.CREATE_COMPARTMENT('SPORT_POLICY', 30, 'MEMBER', 'Member');
    SA_COMPONENTS.CREATE_COMPARTMENT('SPORT_POLICY', 40, 'SECURITY', 'Security');

    -- 3. Groups
    SA_COMPONENTS.CREATE_GROUP('SPORT_POLICY', 1, 'SYSTEM', 'System');
END;
/

-- 4. Tạo Labels (Bổ sung để khớp hoàn toàn với Trigger phân nhãn)
BEGIN
    SA_LABEL_ADMIN.CREATE_LABEL('SPORT_POLICY', 1001, 'PUBLIC:MATCH:SYSTEM');
    SA_LABEL_ADMIN.CREATE_LABEL('SPORT_POLICY', 1002, 'PUBLIC:TEAM:SYSTEM');
    SA_LABEL_ADMIN.CREATE_LABEL('SPORT_POLICY', 2001, 'INTERNAL:MATCH:SYSTEM');
    SA_LABEL_ADMIN.CREATE_LABEL('SPORT_POLICY', 2002, 'INTERNAL:TEAM:SYSTEM');
    SA_LABEL_ADMIN.CREATE_LABEL('SPORT_POLICY', 3001, 'CONFIDENTIAL:MEMBER:SYSTEM');
    
    -- ĐÃ FIX: Thêm các nhãn rời rạc để hỗ trợ hàm CHAR_TO_LABEL trong Trigger
    SA_LABEL_ADMIN.CREATE_LABEL('SPORT_POLICY', 4001, 'SECRET:MEMBER:SYSTEM');
    SA_LABEL_ADMIN.CREATE_LABEL('SPORT_POLICY', 4002, 'SECRET:SECURITY:SYSTEM');
    SA_LABEL_ADMIN.CREATE_LABEL('SPORT_POLICY', 4003, 'SECRET:MEMBER,SECURITY:SYSTEM');
END;
/

-- 5. Áp dụng Policy lên Bảng
BEGIN
    LBAC_POLICY_ADMIN.APPLY_TABLE_POLICY(
        policy_name   => 'SPORT_POLICY',
        schema_name   => 'SPORTS_OWNER',
        table_name    => 'AUDIT_LOG',
        table_options => 'READ_CONTROL'
    );
END;
/

-- TRIGGER DÁN NHÃN ĐỘNG (MAC)
CONN SPORTS_OWNER/CNTT2026!;

CREATE OR REPLACE TRIGGER TRG_AUDIT_LOG_OLS
BEFORE INSERT ON AUDIT_LOG
FOR EACH ROW
BEGIN
    CASE :NEW.ObjectName
        WHEN 'TRAN_DAU' THEN
            :NEW.OLS_LABEL := CHAR_TO_LABEL('SPORT_POLICY', 'INTERNAL:MATCH:SYSTEM');
        WHEN 'DOI_THI_DAU' THEN
            :NEW.OLS_LABEL := CHAR_TO_LABEL('SPORT_POLICY', 'INTERNAL:TEAM:SYSTEM');
        WHEN 'PHAN_CONG_TRAN_DAU' THEN
            :NEW.OLS_LABEL := CHAR_TO_LABEL('SPORT_POLICY', 'INTERNAL:MATCH:SYSTEM');
        WHEN 'THANH_VIEN_DOI' THEN
            :NEW.OLS_LABEL := CHAR_TO_LABEL('SPORT_POLICY', 'CONFIDENTIAL:MEMBER:SYSTEM');
        WHEN 'USER_INFO' THEN
            :NEW.OLS_LABEL := CHAR_TO_LABEL('SPORT_POLICY', 'SECRET:MEMBER:SYSTEM');
        ELSE
            :NEW.OLS_LABEL := CHAR_TO_LABEL('SPORT_POLICY', 'SECRET:SECURITY:SYSTEM');
    END CASE;
END;
/


-- KHỞI TẠO TÀI KHOẢN APP & CẤP QUYỀN CLEARANCE
CONN SYSTEM/manager;

BEGIN
    EXECUTE IMMEDIATE 'CREATE USER BTC_APP IDENTIFIED BY "App2026#"';
    EXECUTE IMMEDIATE 'CREATE USER TD_APP IDENTIFIED BY "App2026#"';
    EXECUTE IMMEDIATE 'CREATE USER TT_APP IDENTIFIED BY "App2026#"';
    EXECUTE IMMEDIATE 'CREATE USER GS_APP IDENTIFIED BY "App2026#"';
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO BTC_APP, TD_APP, TT_APP, GS_APP';
EXCEPTION WHEN OTHERS THEN NULL; END; -- Bỏ qua nếu user đã tồn tại
/

CONN SEC_ADMIN/SEC_ADMIN;

-- Gán nhãn cho Ban Tổ Chức
BEGIN
    SA_USER_ADMIN.SET_USER_LABELS(
        policy_name     => 'SPORT_POLICY',
        user_name       => 'BTC_APP',
        max_read_label  => 'SECRET:MEMBER,SECURITY:SYSTEM',
        max_write_label => 'SECRET:MEMBER,SECURITY:SYSTEM'
    );
END;
/

-- Gán nhãn cho Trưởng đoàn
BEGIN
    SA_USER_ADMIN.SET_USER_LABELS(
        policy_name     => 'SPORT_POLICY',
        user_name       => 'TD_APP',
        max_read_label  => 'CONFIDENTIAL:MEMBER:SYSTEM',
        max_write_label => 'CONFIDENTIAL:MEMBER:SYSTEM'
    );
END;
/

-- Gán nhãn cho Trọng tài
BEGIN
    SA_USER_ADMIN.SET_USER_LABELS(
        policy_name     => 'SPORT_POLICY',
        user_name       => 'TT_APP',
        max_read_label  => 'INTERNAL:MATCH:SYSTEM',
        max_write_label => 'INTERNAL:MATCH:SYSTEM'
    );
END;
/

-- Gán nhãn cho Giám sát
BEGIN
    SA_USER_ADMIN.SET_USER_LABELS(
        policy_name     => 'SPORT_POLICY',
        user_name       => 'GS_APP',
        max_read_label  => 'INTERNAL:TEAM:SYSTEM',
        max_write_label => 'INTERNAL:TEAM:SYSTEM'
    );
END;
/

BEGIN
    SA_USER_ADMIN.SET_USER_LABELS(
        policy_name     => 'SPORT_POLICY',
        user_name       => 'SEC_ADMIN',
        max_read_label  => 'SECRET:MEMBER,SECURITY:SYSTEM',
        max_write_label => 'SECRET:MEMBER,SECURITY:SYSTEM'
    );
END;
/

BEGIN
    SA_USER_ADMIN.SET_USER_LABELS(
        policy_name     => 'SPORT_POLICY',
        user_name       => 'SPORTS_OWNER',
        max_read_label  => 'SECRET:MEMBER,SECURITY:SYSTEM',
        max_write_label => 'SECRET:MEMBER,SECURITY:SYSTEM'
    );
END;
/


PROMPT OLS MASKING AND CLEARANCE POLICIES CONFIGURED SUCCESSFULLY